
package it.fperfetti.asos.botteghino.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FornitoreService", targetNamespace = "http://fornitore-paasfab.rhcloud.com/jboss-as-helloworld-ws/FornitoreService", wsdlLocation = "http://fornitore-fabioperfetti.rhcloud.com/jboss-as-helloworld-ws/FornitoreService?wsdl")
public class FornitoreService_Service
    extends Service
{

    private final static URL FORNITORESERVICE_WSDL_LOCATION;
    private final static WebServiceException FORNITORESERVICE_EXCEPTION;
    private final static QName FORNITORESERVICE_QNAME = new QName("http://fornitore-paasfab.rhcloud.com/jboss-as-helloworld-ws/FornitoreService", "FornitoreService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fornitore-fabioperfetti.rhcloud.com/jboss-as-helloworld-ws/FornitoreService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORNITORESERVICE_WSDL_LOCATION = url;
        FORNITORESERVICE_EXCEPTION = e;
    }

    public FornitoreService_Service() {
        super(__getWsdlLocation(), FORNITORESERVICE_QNAME);
    }

    public FornitoreService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORNITORESERVICE_QNAME, features);
    }

    public FornitoreService_Service(URL wsdlLocation) {
        super(wsdlLocation, FORNITORESERVICE_QNAME);
    }

    public FornitoreService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORNITORESERVICE_QNAME, features);
    }

    public FornitoreService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FornitoreService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FornitoreService
     */
    @WebEndpoint(name = "Fornitore")
    public FornitoreService getFornitore() {
        return super.getPort(new QName("http://fornitore-paasfab.rhcloud.com/jboss-as-helloworld-ws/FornitoreService", "Fornitore"), FornitoreService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FornitoreService
     */
    @WebEndpoint(name = "Fornitore")
    public FornitoreService getFornitore(WebServiceFeature... features) {
        return super.getPort(new QName("http://fornitore-paasfab.rhcloud.com/jboss-as-helloworld-ws/FornitoreService", "Fornitore"), FornitoreService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORNITORESERVICE_EXCEPTION!= null) {
            throw FORNITORESERVICE_EXCEPTION;
        }
        return FORNITORESERVICE_WSDL_LOCATION;
    }

}
